coverage:
  status:
    project:
      default: off
      unit:
        flags:
          - unit
      integration:
        flags:
          - integration

flags:
  unit: {}
  integration: {}

ignore:
  - 'packages/arb-tx-aggregator/arbostestcontracts'
  - 'packages/arb-validator-core/ethbridgecontracts'
  - 'packages/arb-validator-core/ethbridgetestcontracts'
  - 'packages/arb-validator-core/arboscontracts'
  - 'packages/arb-avm-cpp/external/keccak'
  - 'tests/fibgo/fibabi.go'
  - 'packages/arb-provider-ethers/src/lib/abi'
  - '**/*.pb.go'
